### ISSUE TITLE
End session | Automatic

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#138]
As an administrator, in order to make sure a user's session remains secure, I want the system to automatically end a user's session in certain circumstances.

**Acceptance Criteria:**
- [ ] The system should automatically end a user's session after 30 minutes of inactivity
- [ ] User should be warned about ^^^ X minutes before it happens; modal should be consistent with:  https://designsystem.digital.gov/components/modal/ (change the "5" to "five" within the message).  The text of the message reads "Your session will end soon.  You’ve been inactive for too long. Your session will automatically end in five minutes."
- [ ] Upon ending the session, the browser no longer recognizes the user's session

**Comment by melchoyce** [comment]
Are these the only two user flows that require designs?

- User should be warned about ^^^ X minutes before it happens
- Upon ending the session, the browser no longer recognizes the user's session

Any other flows missing?

**Comment by mark-meyer** [comment]
@melchoyce I wonder if `Upon ending the session, the browser no longer recognizes the user's session` actually needs design. We might be able to treat it just like clicking the exit button and send them back to the home page.

**Comment by melchoyce** [comment]
Yeah, the only exception I can think of where we might want to display a notice or something is if someone's email link has expired, but they try to access the site with it anyway?

**Comment by melchoyce** [comment]
For "User should be warned about ^^^ X minutes before it happens", I think we can use the "Open modal with forced action" example here: https://designsystem.digital.gov/components/modal/

**Comment by mark-meyer** [comment]
@melchoyce & @JessicaMarine1 if you want to see what we display now when a user's link has expired (or is invalid), you can just change the token in the url.  For example: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/quiz/training_travel/?t=4e04e01c-f5a6-439a-b743-8ee91fab690d

**Comment by melchoyce** [comment]
Cool. I wondering if we should use an error notice styling instead of warning, what do y'all think?

**Comment by mark-meyer** [comment]
I have no problem with that. We wrote the alert as a vue component that take on any of the uswds color/style choices.

**Comment by mark-meyer** [comment]
At grooming can we talk about ending the session when closing tabs/windows? This is doable (and maybe preferable), but is a significant difference from what we are doing now.

**Comment by melchoyce** [comment]
Warning once you're logged out due to inactivity:

![image](https://github.com/GSA/smartpay-training/assets/2846578/3deeab55-3e8b-4414-81bc-2bdc1ea568d2)
[Figma link](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?node-id=948-15437&t=jC8SbQ6WYSRmVUyP-4)

Text: "Your session has timed out due to inactivity. Log in again to take a training or access past certificates."

**Comment by mark-meyer** [comment]
@melchoyce Question about the alert. The `Start a new session` is underlined. Is that supposed to be a link and if so to where? I don't think it's going to be feasible to take the user back to where they came from without some pretty heavy refactoring [this page is a static html page so even that dynamic message is kind of complicated].

**Comment by JessicaMarine1** [comment]
I would suggest leaving it just at "Your session has timed out due to inactivity."

**Comment by mark-meyer** [comment]
I like that idea @JessicaMarine1.

I want to add that redirecting to the home page is not a technical requirement. It is also possible to stay in the same page. If you were looking at certificates or in the test flow, this would put you back in the state with the same UI you get when you first go to the page (asking for an email address). 

Another option is instead of redirecting to the home page with a message, change the modal to say your session has timeout and leave it up to the user to close the window or press a button to go back to the main page.

**Comment by JessicaMarine1** [comment]
@A-L33 what would you like the user experience to be?

In my opinion, re-routing to the homepage is the safest option, especially if someone is at a public terminal.

**Comment by A-L33** [comment]
@mark-meyer Agree with Jessica.  Let's take out the second sentence of the alert.  So the user is redirected to the homepage after time out with the message "Your session has timed out due to inactivity."  Let me know if I am missing anything,

**Comment by melchoyce** [comment]
Ah, in that case, I'm good to just go with "your session has timed out due to inactivity."

**Comment by melchoyce** [comment]
Did some quick desktop testing!

When I let it time out all the way, I get a browser alert in Chrome:

![Screen Shot 2023-05-12 at 12 32 28 PM](https://github.com/GSA/smartpay-training/assets/2846578/c868b02c-3582-4f44-b4a4-68ea4e40414a)

Which steals focus from any other tab that's open which makes sense, but could also be really jarring without any context if you got distracted and switched over to your email and didn't see the warning modal on the test site:

![Screen Shot 2023-05-12 at 12 31 54 PM](https://github.com/GSA/smartpay-training/assets/2846578/5b9e8420-b9a4-4aa1-93b0-24d88065f7f5)

If I select "leave" it works as expected:
 
![Screen Shot 2023-05-12 at 12 32 05 PM](https://github.com/GSA/smartpay-training/assets/2846578/d5aeea64-138a-40e3-a805-5f28cfb1c129)

But if I select cancel, it redirects me here:

![Screen Shot 2023-05-12 at 12 32 35 PM](https://github.com/GSA/smartpay-training/assets/2846578/c4f1f725-80a6-4cf3-9105-7dca7afd5c20)

Which isn't really a _problem_, but since the error notice isn't shown on this page, there's no context for the logout. 

Unsure if this is just a Chrome issue, or if there's anything we can do about it, but it feels a little weird.

**Comment by A-L33** [comment]
If I submit my email and authenticate with the link, then I'm "in session."  If I do not start the quiz, the pop up box comes up just fine and a few seconds later it kicks me back to the homepage with the banner indicating I've been timed out.  If I end the session, it takes me back to the homepage with no banner.  This makes sense.

If I start a quiz and am idle, the pop up comes up.  A few seconds later, a notification pops up indicating that my progress will be lost but the box stays open like this:
![image](https://github.com/GSA/smartpay-training/assets/116583391/af52f337-1af0-4b37-b185-b3a1f8d02d48)

If I actively select "Leave" it takes me it kicks me back to the homepage with the banner indicating I've been timed out.  If i select "cancel," it kicks me to the email page with no banner. not the home page:
![image](https://github.com/GSA/smartpay-training/assets/116583391/61a9edc1-b1d9-430a-9900-6ac650f01231)

Question, do we want the two boxes interacting like that?

**Comment by A-L33** [comment]
@melchoyce Looks like we experienced the same thing.  I was a little concerned that the "are you sure you want to leave" box doesn't auto timeout by itself but not sure if there's anything we can do about that.

**Comment by mark-meyer** [comment]
Okay, I think I got this worked out @melchoyce (and took a little time to prevent the flash of the logged out quiz page). Try giving this a spin: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/mmeyer/138-timeout/

**Comment by JessicaMarine1** [comment]
@mark-meyer this is looking good to me. I tested the quiz and past certificates flow and it kept me "signed in" as expected; and prompted and signed out as expected.

**Comment by melchoyce** [comment]
Looks great to me on desktop and mobile!

**Comment by mark-meyer** [comment]
Awesome. Thank you both. I will go ahead and make the timeouts the proper duration and make a pull request. Wei or Jeff can merge it in when they are back.

**Comment by weiwang-gsa** [comment]
@melchoyce @A-L33 This is ready for QA: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/

**Comment by A-L33** [comment]
Done!  Took me awhile to QA because I had to let it timeout a couple of times!
