### ISSUE TITLE
Quiz Mobile Access

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#15]
As a user, I want to access and take quizzes from a mobile device, so I can complete required quizzes without using a laptop.

Acceptance criteria:
- User is able to access & take quizzes from a mobile device
  - Note: this story is intended to capture design tweaks, if any, that might be needed for the quiz flow on mobile
- See [design changes](https://github.com/GSA/smartpay-training/issues/15#issuecomment-1522501448) in comment below

**Comment by JessicaMarine1** [comment]
@melchoyce for this story, please test the quiz functionality on mobile and see if you have any design changes.

**Comment by melchoyce** [comment]
Let's make the quiz full-width once your screen hits under that 1024px breakpoint:

**Before**
![Screen Shot 2023-04-25 at 6 21 16 PM](https://user-images.githubusercontent.com/2846578/234417013-344c79b1-8383-4b9f-b16c-5df4be5ed37c.png)

**After**
![Screen Shot 2023-04-25 at 6 22 55 PM](https://user-images.githubusercontent.com/2846578/234417175-9c977291-af3d-4697-bd11-e12fee69a011.png)

Otherwise, everything LGTM 👍

**Comment by A-L33** [comment]
@melchoyce Double check cert access.

**Comment by JessicaMarine1** [comment]
@melchoyce @A-L33 I tested the quiz-->download certificate flow on mobile. It worked on my iPhone. It downloaded the cert and prompted me to save it locally to my phone, which I did without issue. Y'all might want to try it just to see if you're cool with the UX.

**Comment by A-L33** [comment]
Just tested it on my phone too and it works great.

**Comment by A-L33** [comment]
Done!
