### ISSUE TITLE
Administrator | Secure Access

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#179]
As an administrator, I need to securely access administrative functions.

**Acceptance criteria:**

- [ ] Administrator can access the system using a multifactor authentication tool (e.g., SecureAuth)
- [ ] Upon logging in, administrator is presented with dashboard where they can search for users by name (see #180)

[DESIGN](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1135-24901)

**Comment by mark-meyer** [comment]
Do we know what steps we need to take to use GSA's SecureAuth login? I [very] quick search for documentation didn't turn up anything obvious.

**Comment by A-L33** [comment]
@melchoyce Below are screenshots


![Image](https://github.com/GSA/smartpay-training/assets/116583391/a303d93a-54e8-4a10-af65-9218888fdb42)

Login Page



![Image](https://github.com/GSA/smartpay-training/assets/116583391/79137fee-cdef-4ef9-b24e-a254848ec312)

2FA page

**Comment by A-L33** [comment]
Inquiry sent to Cloud.gov ISSM re: MFA tools.  For more information re: OKTA, Manish in IQ can be POC.

**Comment by melchoyce** [comment]
Do we have an idea of which MFA service we're going to use, and whether that would impact the UI at all? If not, I'll go ahead and design something generic.

**Comment by A-L33** [comment]
@melchoyce We're exploring SecureAuth at the moment.  @jfredrickson5 does it look like there may be UI impact based on the documentation?

**Comment by jfredrickson5** [comment]
Based on what I've seen so far, I believe the entire login flow will be external. Things like the username/password fields, MFA code entry, etc, will all happen outside of our website in SecureAuth. Once SecureAuth authenticates the user, the user will be redirected to a given page (in this case, the admin dashboard). So we don't have control over that design. I believe we'll only need to think about:

- A link to the SecureAuth login (or perhaps not; since only administrative users need to login, it might make more sense to not have a public facing login link, which could confuse users)
- What an admin user should see if they're logged out but then try to visit a page that requires login (e.g., should they see a message like "you need to login to use this feature" with a link to SecureAuth login?)

**Comment by jfredrickson5** [comment]
Documentation for two possible approaches to SecureAuth integration:
- [SecureAuth via SAML](https://docs.secureauth.com/2006/index.html?lang=en)
- [cloud.gov UAA](https://cloud.gov/docs/management/leveraging-authentication/)

**Comment by melchoyce** [comment]
> * A link to the SecureAuth login (or perhaps not; since only administrative users need to login, it might make more sense to not have a public facing login link, which could confuse users)

@A-L33 What do you think about this? Would you prefer a link somewhere on the SmartPay site, or would you prefer for your team to use a bookmarked link to login?

**Comment by A-L33** [comment]
@rebekahperillo Thoughts here?  For admin access, I think it would be nice to have a link somewhere but it might be more secure to have our team enter through a non-public facing door.  I vote bookmark but thoughts?

**Comment by rebekahperillo** [comment]
Agreed - bookmark for admin access, rather than displaying a link on the
page.

Rebekah Knouse Perillo
Business Management Specialist
Center for Charge Card Management
Office of Professional Services and Human Capital Categories
Federal Acquisition Service, U.S. General Services Administration

*301-938-5257*
Follow the GSA SmartPay program on social media...Tweet with us on Twitter
<https://twitter.com/GSASmartPayNews> and friend us on Facebook
<https://www.facebook.com/GSASmartPayNews/>!

[image: image.png]

**Comment by melchoyce** [comment]
Is this kind of what we're thinking for an "access denied" screen?

![image](https://github.com/GSA/smartpay-training/assets/2846578/0d76f956-64a4-4cd6-b8c7-405be500a50d)
[Figma](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=993-16895&t=mYbcFZgCwpUcvWtU-4)

**Comment by rebekahperillo** [comment]
@melchoyce Look good to me, thank you! @A-L33 , thoughts?

**Comment by A-L33** [comment]
@melchoyce Looks good.  Just so I am clear, we would bookmark this URL and only those (i.e., our admins) will have access to this screen.  Then we sign in with secureauth?  Thank you!

**Comment by melchoyce** [comment]
Yup! And if your team finds that doesn't work for you in practice, we could think about adding a discrete link in the future.

**Comment by klohman** [comment]
@mark-meyer @JessicaMarine1 What is the expected /anticipated behavior when a user attempts to login but is not actually authorized for this access? Is this taken care of via the SecureAuth flow, or something we need to design for?

**Comment by JessicaMarine1** [comment]
@klohman I _assumed_ it was handled by SecureAuth...

**Comment by mark-meyer** [comment]
@klohman / @JessicaMarine1 I think there's a little work to do on this still. 

There is more than one way auth can fail:

1. You do no provide a good name / password (or MFA). In this case, SecureAuth handles this. It will prompt for correct credentials.
2. You successfully authenticate with SecureAuth (i.e. you demonstrate you are who you say you are), but you are not an admin in the system. This part is currently half-baked. (It brings you back to the admin panel, but you can't actually do anything). Here it should probably display an alert saying something like, 'You are not authorized to access this function.'

**Comment by klohman** [comment]
> @klohman / @JessicaMarine1 I think there's a little work to do on this still.
> 
> There is more than one way auth can fail:
> 
> 1. You do no provide a good name / password (or MFA). In this case, SecureAuth handles this. It will prompt for correct credentials.
> 2. You successfully authenticate with SecureAuth (i.e. you demonstrate you are who you say you are), but you are not an admin in the system. This part is currently half-baked. (It brings you back to the admin panel, but you can't actually do anything). Here it should probably display an alert saying something like, 'You are not authorized to access this function.'

How about this? 
![image](https://github.com/GSA/smartpay-training/assets/18366192/976b967b-c4ae-47b2-b432-a909b0a85cd9)

**Comment by rebekahperillo** [comment]
Tested and all looks good, thank you!
