### ISSUE TITLE
Quiz Progress Not Saved

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-training#18]
As a administrator, I want to notify users that quizzes are not ""bookmarked,"" so users understand that if they navigate away from a quiz without completing it, progress will be lost.

Acceptance criteria:
- Prior to accessing a quiz, user is provided a message indicating that users will lose progress is the quiz is not completed
- If a user attempts navigate away from the quiz, a warning is sent indicating that users will lose progress is the quiz is not completed
- If a user attempts to close the tab / browser prior to completing the quiz, a warning is sent indicating that users will lose progress is the quiz is not completed

**Comment by JessicaMarine1** [comment]
@actuallyjenn you might want to add something for this to your prototype

**Comment by mark-meyer** [comment]
Doing some research on this card. The basic functionality is fairly easy to implement, but because this sort of thing has been abused a lot in the past (i.e. "Closing this tab will make your computer explode!") browsers no longer allow you much customization — you basically get the pop-up the browser gives everyone. 

I am going by the docs here: https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event

If anyone sees examples (or has one in mind) of this other than the default, I can investigate.

**Comment by actuallyjenn** [comment]
I have this on my list to include in my prototype, and I'm not sure from a technical perspective, but I was going to use the [USWDS modal component](https://designsystem.digital.gov/components/modal/) for navigating elsewhere within the site and was referencing how the [VA healthcare application](https://www.va.gov/health-care/apply/application/id-form) handles closing out the browser. In this example, you have to fill out the first part of the form, and then once you're in the form and try to leave the tab, there's the browser pop-up below (I use chrome):
![image](https://user-images.githubusercontent.com/6501138/228701516-0a239735-5d84-42c1-b4a6-e84caa410eea.png)

**Comment by mark-meyer** [comment]
@actuallyjenn I think the popup in on the VA site is _the_ browser popup. I don't think we can edit the design or language. If this will work (I _think_ it might have to), it's not hard to implement. There are some edge cases for mobile mentioned here: https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event#usage_notes
