### ISSUE TITLE
Failed quiz instructions

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#241]
During [usability testing](https://docs.google.com/presentation/d/1CXmW0nJq9ehc03xjpmXbpzjazEJwCPFXACDK6zslrto/edit?pli=1#slide=id.g24d24373237_0_0), users suggested that the failed quiz instructions could be more clear.

![Image](https://github.com/GSA/smartpay-training/assets/92383362/f0041167-44bd-4882-a174-24bf949328fa)

Change language in red box to:
You got 1 of 5 questions correct for a score of 20%. You need 75% to pass. Please try again.

**Comment by klohman** [comment]
## Design mockup 
![image](https://github.com/GSA/smartpay-training/assets/18366192/8eb07790-52c7-4e52-9fde-10658690ed14)

**Comment by weiwang-gsa** [comment]
@klohman this is ready for design review: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/

Please note, the quiz email link is still link to main branch, you will have to manually copy the URL out, and replace below portion in red by "https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/" in order to take quiz at the staging branch. 
![Image](https://github.com/GSA/smartpay-training/assets/119954777/8817284c-0e8b-484d-8157-4592d0bcca7f)

**Comment by klohman** [comment]
@rebekahperillo @A-L33 Ready for QA

**Comment by rebekahperillo** [comment]
@klohman Moving to "DONE"! Thank you!
