### ISSUE TITLE
Technical Debt

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#251]
Before picking up _new_ work, allow the engineers time to for code review / refactoring

**Comment by mark-meyer** [comment]
One thing that might be good to do since we have the time is update to the latest version on FastAPI. The new versions uses the new major version of Pydantic, which has some breaking changes (but is apparently _much_ faster). I did this on the 889 tool and it required some plumbing changes…it will probably be a bit more work here.

**Comment by mark-meyer** [comment]
More work is happening under this mostly around shoring up unit tests on the training backend including:

Bring tests for loginless api to 100% https://github.com/GSA/smartpay-training/pull/304
Add tests for Agency sorting (now 100%): https://github.com/GSA/smartpay-training/pull/302
Tests for email and certificates to 100%: https://github.com/GSA/smartpay-training/pull/298

**Comment by rebekahperillo** [comment]
@mark-meyer Is there anything to test/review here? Suggestions? Thank you!
