### ISSUE TITLE
Training | Travel Card Training for A/OPCs

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#58]
As a user of the site, I want to access **Travel Card Training for A/OPCs** without registering (providing an email), so I can view/print training materials.

**Pre-Condition:**
- [Training material content](https://docs.google.com/document/d/1ksVhM0ZVRkFpHPRHarwwF9PevCMbxX-kdfn0A9u96UA/edit#) is complete ☑︎

**Acceptance criteria:**
- [ ] Users can progress through each lesson of the training in the browser without providing an email address 
   - Note: this should have the same exact look / experience as the [Travel Card Training for Card/Account Holders & Certifying Officials](https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/training_travel/)
- [ ] Please add external link icons where appropriate (any link outside of GSA SmartPay training site; Mark has a script for this)
- [ ] Users can access quiz registration form from end of training material
- [ ] Users can view & print a 508 compliant, print-friendly version of the full training

**Comment by A-L33** [comment]
@JessicaMarine1 @brentryanjohnson @johnbeallgsa Program completed scrub of this training.  Link above.

**Comment by mark-meyer** [comment]
@A-L33 We have some inconsistency around the way we refer to the quiz related to A/OPC quizzes in the code — I think we just had some holding text, but want to check before changing it because we use `Training for Program Coordinators` on the home page. We have this in the header for the quiz related to this training:

![Image](https://user-images.githubusercontent.com/7340303/234724945-22a56388-1097-4231-8493-a66e342ce2a7.png)

Should the small text have the whole text: `Agency/Organization Program Coordinators (A/OPCs)`.

**Comment by A-L33** [comment]
@mark-meyer Good catch.  I think using "Program Coordinators" in the top nav bar is fine because we're using it to address an audience type.  When we refer to the course itself (and the associated quiz), we should use the course's name, which is "GSA SmartPay(r) [business line] Training for Agency/Organization Program Coordinators."  The large white text in the blue box is fine and I looked at the homepage again to check for consistency and I'm fine with the language there too.  Let me know if this doesn't make sense.

**Comment by A-L33** [comment]
Done!
