### ISSUE TITLE
Spinner Graphic for Slow Load Functions

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#90]
When the site is hitting the database, it might appear _slow_ to some users. As a result, we might want to consider a "spinner" graphic to indicate to user that the system is working:

https://gist.github.com/erikcox/7e96d031d00d7ecb1a2f
https://github.com/uswds/uswds/issues/4346
https://carbondesignsystem.com/patterns/loading-pattern/
https://design.cms.gov/components/spinner/?theme=core

**Acceptance Criteria:**

- [ ] Introduce "spinner" whenever system is hitting the database and user is waiting for a response:
   - [ ] Entering email for loginless access to quiz
   - [ ] Entering email for loginless access to past certificates

**Comment by melchoyce** [comment]
@weiwang-gsa What are some errors that a user might encounter?

**Comment by weiwang-gsa** [comment]
@melchoyce there are validation errors on email/name/agency etc, but those are client side validation errors ( which response really fast and doesn't need to talk to API). and there are some server errors, typically is API is up running or DB has no error, user will not see these errors, if there is exception on the server side or DB connection is down, then below error will show up for the end user : 

- Sorry, we had an error connecting to the server.
- Error contacting server

**Comment by weiwang-gsa** [comment]
@melchoyce this is ready for your review: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/

**Comment by melchoyce** [comment]
Sorry, was drafting this and then ran to do a tree test and forgot to send 😩 

Looks great on desktop!

It's too fast to get a screenshot on my phone, but the full-width button seems to resize to its narrower desktop size when the spinner shows up. Maybe the spinner can display below? Here's a quick mockup:

![image](https://github.com/GSA/smartpay-training/assets/2846578/5857a76a-5c9c-4ae5-ab53-9218fa5db306)

In contrast, the responsive view on desktop has it weirdly centered instead of displaying next to the button:
![Screen Shot 2023-05-16 at 10 56 45 AM](https://github.com/GSA/smartpay-training/assets/2846578/116db8ed-7161-4fb5-8228-cd4c085c3aee)

We should have it match wider screens and stay next to the button.

Let me know if this feedback makes sense!

**Comment by weiwang-gsa** [comment]
@melchoyce Thanks for feedback, I like the idea that displaying the loading icon under the submit button. Will make the change accordingly

**Comment by weiwang-gsa** [comment]
@melchoyce @A-L33 it is ready for QA: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/site/gsa/smartpay-training/

**Comment by melchoyce** [comment]
Looks good to me as well!
